build:
  automatic: True
  always_full_update: True
  depends_on: "pydockerx11/base/fedora:36"
  image: "pydockerx11/base/fedora"
  tag: "36-x11"
  dockerfile_update:
    - USER root
    - RUN dnf update -y
    - USER sandbox

