FROM pydockerx11/base/ubuntu:20.04-x11
USER root
ADD cache/arduino-legacy-latest.tar.xz /opt
WORKDIR /opt
RUN find /opt -maxdepth 1 -mindepth 1 -type d -exec mv {} arduino-ide \;
ENTRYPOINT [ "/opt/arduino-ide/arduino" ]
USER sandbox
